version: "3.7"

services:

    metrics:
        image: influxdb:latest
        ports:
            - 8086:8086
        volumes:
            - metrics-data:/var/lib/influxdb
        environment:
            - INFLUX_SERIES
            - INFLUX_BUCKET
            - INFLUX_ORG
            - INFLUX_URL
            - INFLUX_TOKEN
            - DOCKER_INFLUXDB_INIT_MODE
            - USE_FAKE_DATA

    collector:
        image: python:3-alpine3.18
        build: ./collector
        restart: "unless-stopped"
        devices:
        - "/dev/ttyUSB0:/dev/ttyUSB0:ro"
        environment:
          - MONGO_CONN
          - MONGO_DB
          - MONGO_COLL

    grafana:
        image: grafana/grafana-oss:latest-ubuntu
        restart: "unless-stopped"
        ports:
            - 3000:3000
        volumes:
            - grafana-data:/var/lib/grafana

volumes:
    metrics-data:
        external: false
    grafana-data:
        external: false
